{
 "title": "NpgSql",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "influxdb" },
   {
    "name": "summarize",
    "query": "5s,10s,30s,1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "environment",
    "query": "SHOW TAG VALUES WITH KEY = \"env\""
   },
   {
    "name": "application",
    "query": "SHOW TAG VALUES WITH KEY = \"app\" WHERE \"env\" =~ /$environment/"
   },
   {
    "name": "server",
    "query": "SHOW TAG VALUES WITH KEY = \"server\" WHERE \"env\" =~ /$environment/ AND \"app\" =~ /$application/"
   }
  ]
 },
 "panels": [
  {
   "title": "Connections",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "Idle Connections",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "npgsql__idle-connections",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "server", "operator": "=~", "value": "/^$server$/" },
      { "condition": "AND", "key": "app", "operator": "=~", "value": "/^$application$/" }
     ]
    },
    {
     "alias": "Busy Connections",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "npgsql__busy-connections",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "server", "operator": "=~", "value": "/^$server$/" },
      { "condition": "AND", "key": "app", "operator": "=~", "value": "/^$application$/" }
     ]
    }
   ]
  },
  {
   "title": "IO Rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "Bytes Written",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "npgsql__bytes-written-per-second",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "server", "operator": "=~", "value": "/^$server$/" },
      { "condition": "AND", "key": "app", "operator": "=~", "value": "/^$application$/" }
     ]
    },
    {
     "alias": "Bytes Read",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "npgsql__bytes-read-per-second",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "server", "operator": "=~", "value": "/^$server$/" },
      { "condition": "AND", "key": "app", "operator": "=~", "value": "/^$application$/" }
     ]
    }
   ]
  },
  {
   "title": "Commands",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "Commands per second",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "npgsql__commands-per-second",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "server", "operator": "=~", "value": "/^$server$/" },
      { "condition": "AND", "key": "app", "operator": "=~", "value": "/^$application$/" }
     ]
    },
    {
     "alias": "Current commands",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "npgsql__current-commands",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "server", "operator": "=~", "value": "/^$server$/" },
      { "condition": "AND", "key": "app", "operator": "=~", "value": "/^$application$/" }
     ]
    }
   ]
  },
  {
   "title": "Prepared Commands",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "Prepared commands ratio",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "npgsql__prepared-commands-ratio",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "server", "operator": "=~", "value": "/^$server$/" },
      { "condition": "AND", "key": "app", "operator": "=~", "value": "/^$application$/" }
     ]
    }
   ]
  },
  {
   "title": "Total Commands",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 12 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "alias": "Total Commands",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "npgsql__total-commands",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "server", "operator": "=~", "value": "/^$server$/" },
      { "condition": "AND", "key": "app", "operator": "=~", "value": "/^$application$/" }
     ]
    }
   ]
  },
  {
   "title": "Connection Pools",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 12 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "alias": "Connection Pools",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "npgsql__connection-pools",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "server", "operator": "=~", "value": "/^$server$/" },
      { "condition": "AND", "key": "app", "operator": "=~", "value": "/^$application$/" }
     ]
    }
   ]
  },
  {
   "title": "Failed Commands",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 12 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "alias": "Failed Commands",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "npgsql__failed-commands",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "server", "operator": "=~", "value": "/^$server$/" },
      { "condition": "AND", "key": "app", "operator": "=~", "value": "/^$application$/" }
     ]
    }
   ]
  }
 ]
}