{
 "title": "System.Runtime Copy",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "influxdb" },
   {
    "name": "summarize",
    "query": "5s,10s,30s,1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "environment",
    "query": "SHOW TAG VALUES WITH KEY = \"env\""
   },
   {
    "name": "application",
    "query": "SHOW TAG VALUES WITH KEY = \"app\" WHERE \"env\" =~ /$environment/"
   },
   {
    "name": "server",
    "query": "SHOW TAG VALUES WITH KEY = \"server\" WHERE \"env\" =~ /$environment/ AND \"app\" =~ /$application/"
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "CPU Usage %",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "system.runtime__cpu-usage",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "server", "operator": "=~", "value": "/^$server$/" },
      { "condition": "AND", "key": "app", "operator": "=~", "value": "/^$application$/" }
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "alias": "Working set",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "system.runtime__working-set",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "server", "operator": "=~", "value": "/^$server$/" },
      { "condition": "AND", "key": "app", "operator": "=~", "value": "/^$application$/" }
     ]
    },
    {
     "alias": "GC Heap Size",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "system.runtime__gc-heap-size",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "server", "operator": "=~", "value": "/^$server$/" },
      { "condition": "AND", "key": "app", "operator": "=~", "value": "/^$application$/" }
     ]
    }
   ]
  },
  {
   "title": "Thread pool",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Thread count",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "system.runtime__threadpool-thread-count",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "server", "operator": "=~", "value": "/^$server$/" },
      { "condition": "AND", "key": "app", "operator": "=~", "value": "/^$application$/" }
     ]
    },
    {
     "alias": "Threadpool queue lenght",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "system.runtime__threadpool-queue-length",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "server", "operator": "=~", "value": "/^$server$/" },
      { "condition": "AND", "key": "app", "operator": "=~", "value": "/^$application$/" }
     ]
    },
    {
     "alias": "Threadpool completed items count",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "system.runtime__threadpool-completed-items-count",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "server", "operator": "=~", "value": "/^$server$/" },
      { "condition": "AND", "key": "app", "operator": "=~", "value": "/^$application$/" }
     ]
    }
   ]
  },
  {
   "title": "GC Heap",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "Gen 0 Size",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "system.runtime__gen-0-size",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "server", "operator": "=~", "value": "/^$server$/" },
      { "condition": "AND", "key": "app", "operator": "=~", "value": "/^$application$/" }
     ]
    },
    {
     "alias": "Gen 1 Size",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "system.runtime__gen-1-size",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "server", "operator": "=~", "value": "/^$server$/" },
      { "condition": "AND", "key": "app", "operator": "=~", "value": "/^$application$/" }
     ]
    },
    {
     "alias": "Gen 2 Size",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "system.runtime__gen-2-size",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "server", "operator": "=~", "value": "/^$server$/" },
      { "condition": "AND", "key": "app", "operator": "=~", "value": "/^$application$/" }
     ]
    },
    {
     "alias": "LOH Size",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "system.runtime__loh-size",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "server", "operator": "=~", "value": "/^$server$/" },
      { "condition": "AND", "key": "app", "operator": "=~", "value": "/^$application$/" }
     ]
    }
   ]
  },
  {
   "title": "Timers",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Active timer count",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "system.runtime__active-timer-count",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "server", "operator": "=~", "value": "/^$server$/" },
      { "condition": "AND", "key": "app", "operator": "=~", "value": "/^$application$/" }
     ]
    }
   ]
  },
  {
   "title": "Alloc Rate",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "Alloc Rate",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "system.runtime__alloc-rate",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "server", "operator": "=~", "value": "/^$server$/" },
      { "condition": "AND", "key": "app", "operator": "=~", "value": "/^$application$/" }
     ]
    }
   ]
  },
  {
   "title": "Locks",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Monitor lock contention count",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "system.runtime__monitor-lock-contention-count",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "server", "operator": "=~", "value": "/^$server$/" },
      { "condition": "AND", "key": "app", "operator": "=~", "value": "/^$application$/" }
     ]
    }
   ]
  },
  {
   "title": "GC",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Gen 0",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "system.runtime__gen-0-gc-count",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "server", "operator": "=~", "value": "/^$server$/" },
      { "condition": "AND", "key": "app", "operator": "=~", "value": "/^$application$/" }
     ]
    },
    {
     "alias": "Gen 1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "system.runtime__gen-1-gc-count",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "server", "operator": "=~", "value": "/^$server$/" },
      { "condition": "AND", "key": "app", "operator": "=~", "value": "/^$application$/" }
     ]
    },
    {
     "alias": "Gen 2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "system.runtime__gen-2-gc-count",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "server", "operator": "=~", "value": "/^$server$/" },
      { "condition": "AND", "key": "app", "operator": "=~", "value": "/^$application$/" }
     ]
    }
   ]
  },
  {
   "title": "Exceptions",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Exceptions count",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "system.runtime__exception-count",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "server", "operator": "=~", "value": "/^$server$/" },
      { "condition": "AND", "key": "app", "operator": "=~", "value": "/^$application$/" }
     ]
    }
   ]
  },
  {
   "title": "Assembly count",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 30 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "alias": "Assembly count",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "system.runtime__assembly-count",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "server", "operator": "=~", "value": "/^$server$/" },
      { "condition": "AND", "key": "app", "operator": "=~", "value": "/^$application$/" }
     ]
    }
   ]
  },
  {
   "title": "Time in GC",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "% time in GC",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "system.runtime__time-in-gc",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "server", "operator": "=~", "value": "/^$server$/" },
      { "condition": "AND", "key": "app", "operator": "=~", "value": "/^$application$/" }
     ]
    }
   ]
  }
 ]
}